name: Frontend CI

on:
  push:
    branches: [main, develop]
    paths:
      - 'apps/frontend/**'
      - 'packages/**'
      - 'package.json'
      - 'yarn.lock'
      - '.github/workflows/frontend.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'apps/frontend/**'
      - 'packages/**'
      - 'package.json'
      - 'yarn.lock'
      - '.github/workflows/frontend.yml'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
      - name: Enable Corepack
        run: corepack enable
      - name: Cache yarn dependencies
        uses: actions/cache@v4
        with:
          path: ~/.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn install --immutable

      - name: Run ESLint
        run: yarn workspace @template/frontend lint

      - name: Check Prettier formatting
        run: yarn workspace @template/frontend format:check

      - name: Run TypeScript type checking
        run: yarn workspace @template/frontend type-check

      - name: Run tests
        run: yarn workspace @template/frontend test
